[project]
name = "facesearcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "opencv-python>=4.13.0.92",
    "pillow>=11.3.0",
    "pyinstaller>=6.19.0",
    "scikit-image>=0.24.0",
    "wxpython>=4.2.4",
]
